version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile-web-service
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "80"
    ports:
      - "8080:80"

  waf:
      build: waf-3
      # ports:
      #     - "8088:80"
      networks:
        envoymesh:
          aliases:
            - waf
      expose:
        - "80"            
  app:
      build: app  
      networks:
        envoymesh:
          aliases:
            - app          

networks:
  envoymesh: {}
